### ISSUE TITLE
Virus doesn't run in windows 7 and linux

### ISSUE THREAD

**Issue by dodatdi** [Pure-L0G1C/Loki#27]
I have 2 questions looking forward to your answer:
1. When I build the virus, it only works on the server itself, running on the virtual machine Windows 7, the error is as shown. 
![Capture](https://user-images.githubusercontent.com/30981111/78207583-4c459380-74cc-11ea-8c6c-b9fd01b1dcdd.PNG)

Is it when the library is missing library? Is there any way to fix the error?
2. Which python file do I want to run virus on linux?
Thank you

**Comment by Pure-L0G1C** [comment]
https://discord.gg/wwcShN
