### ISSUE TITLE
Payload binary does not exist; please generate it

### ISSUE THREAD

**Issue by mandroid19** [Pure-L0G1C/Loki#29]
Hi,
I tried to connect back from my Windows VM(client) to Linux VM(server) however the server says: Payload binary does not exist; please generate it

I tried to compile the agent/bot/template_payload.py, but it says: NameError: name 'auto_persist' is not defined.

**Comment by Pure-L0G1C** [comment]
You don't run that directly. You have to run builder.py
`python builder.py -i 127.0.0.1 -p 8080 -n payload_name`

**Comment by mandroid19** [comment]
I have compiled it. But with port 8084, because the server won't start with
8080 port.
- So I compiled the file with builder called test8084.exe
- I copy it to my windows machine.
- I start the loki server with 127.0.0.1 8084
- I start the test8084.exe on windows
- My linux command line with loki says: payload binary does not exist;
please generate it
- The windows can see my linux even if I nc -lvp 8084 I can see that a
connection is coming to my way
- The server does not show any bot
- If I click again on the test8084.exe (on windows), the loki server says
again the same thing in the command line.
