### ISSUE TITLE
Screenshare command not working 

### ISSUE THREAD

**Issue by Meeeee6623** [Pure-L0G1C/Loki#30]
The screenshare command says that it has started, and responds to the stop command, but the webpage remains blank the whole time. Additionally, the -t modifier for the compiler does not appear to exist for me. Last of all, could someone please tell me where screenshots and files are downloaded? 
Thanks!

**Comment by Pure-L0G1C** [comment]
Thanks for letting me know, the issue should be fixed now. The -t modifier is no longer a thing, the generator only outputs exe files from now on. I've also added a new feature that saves downloaded content into a directory named downloads; it can be found on the same directory level as the loki.py file.

**Comment by Meeeee6623** [comment]
Alright, thanks!
