### ISSUE TITLE
Fatal error detected - Failed to execute script

### ISSUE THREAD

**Issue by sp00kyhacker** [Pure-L0G1C/Loki#7]
I am getting the error "failed to execute script stub2"

I followed exactly the directions on this video.

https://www.youtube.com/watch?v=aBEtwJ5gxSw

The file it generates is a bit bigger than the one in the video, I'm assuming as there's been some updates since then. It appears with the error but generates the second file "_stub2.exe" as an empty 0kb file that does nothing essentially. I'm on Windows 10 using python3.6

Also for my server setup I'm using a vpn IP with port forwarded, the server is started in the panel and loki.py is running fine. Just seems to be the builder, instead of 127.0.0.1 in the builder command I put my VPN server public IP and the port that is forwarded.

Thanks for taking the time to read!

**Comment by Pure-L0G1C** [comment]
Yeah I changed something yesterday but I didn’t test the chance because I was in a rush. I will test it today and fix the errors

**Comment by sp00kyhacker** [comment]
Thanks brother. I'll be waiting for your reply :D I'm in no rush.

**Comment by sp00kyhacker** [comment]
I've tried reverting the change you made yesterday from "create_persist" back to "create_task" and I still received the same error. Hopefully this helps with debugging. I also have latest .net framework, I'm not sure if that will effect things.

**Comment by Pure-L0G1C** [comment]
Okay. What exactly is the issue you’re getting?

**Comment by sp00kyhacker** [comment]
I've noticed under /build/stub2/warn-stub2.txt there is a warning for a list of 15 or so modules that are missing. I used pip3.6 to install the requirements.txt and everything went successfully, so I ran into a dead end there. Not too sure where I went wrong

**Comment by Pure-L0G1C** [comment]
I just added support for Python 3.7, can you check if the problem went away

**Comment by sp00kyhacker** [comment]
Shows a lot of libraries not found while trying to build. Also when I run pip install -r requirements.txt it shows venom 425 requires certain dependencies and that they're not installed. It keeps loading new commands then automatically clears the CMD when it finishes building so I cant stop it long enough to read what libraries exactly.

**Comment by sp00kyhacker** [comment]
This is with using python 3.7

**Comment by Pure-L0G1C** [comment]
Yeah, it do be like that. Pyinstaller shows a lot of libraries not found errors, just ignore it

**Comment by sp00kyhacker** [comment]
It worked! Thanks so much :D Im curious to know, on a separate note, what would be the correct compatibility type to use when crypting the payload? (vbc.exe, self inject, applaunch, cvtres, Manual Image Map, .net self inject) Those types are my main options

**Comment by Pure-L0G1C** [comment]
It's pointless encrypting the payload. It will be detected when it's decrypted

**Comment by sp00kyhacker** [comment]
So now way to make it undetectable from AV then? Or different method?

**Comment by Pure-L0G1C** [comment]
I mean if you don't upload it to Virus-total it should stay FUD. I'll change it once it starts getting detected

**Comment by sp00kyhacker** [comment]
Sounds good man. Thanks for all the help. And I use scanmybin

**Comment by Pure-L0G1C** [comment]
No don't

**Comment by Pure-L0G1C** [comment]
Not use any scanners

**Comment by Pure-L0G1C** [comment]
That's like the first rule

**Comment by sp00kyhacker** [comment]
I havent used it to scan this stub, but I thought just to not use ones that distribute? Antiscan, Scanmybin, these ones don't distribute.

**Comment by Pure-L0G1C** [comment]
Okay, I just just making sure.

**Comment by Pure-L0G1C** [comment]
This program was f**king painful to write, I don't want it getting messed up

**Comment by sp00kyhacker** [comment]
Np I paid for subscription just for these testing purposes :D Once im home im going to test it on malwarebytes, windows defender and if it gets hit im going to try couple crypting processes and obfuscate, see if it still connects and the tasks work, hopefully.

**Comment by Pure-L0G1C** [comment]
Alright.

**Comment by Pure-L0G1C** [comment]
@sp00kyhacker I added encryption to the payload. Encryption is just for transfer though, nothing else
