### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Rabb2269** [Pure-L0G1C/Loki#9]
XXX@parrot]─[~/Loki]
└──╼ $python loki.py
Traceback (most recent call last):
  File "loki.py", line 9, in <module>
    from lib.server.server import Server
  File "/home/rabb/Loki/lib/server/server.py", line 8, in <module>
    from lib import const
ImportError: cannot import name const

Assistance friend.

**Comment by Pure-L0G1C** [comment]
I write the program for Python 3.6+

**Comment by Pure-L0G1C** [comment]
And it just work best in Windows 10

**Comment by Rabb2269** [comment]
Ahh i seen it said Kali Linux and Parrot OS is kali linux with there own throw in on stuff.

**Comment by Pure-L0G1C** [comment]
Yes the server can run on Linux, but when you want to make an executable you should use Windows

**Comment by Rabb2269** [comment]
Can you assist me in setting up server?
I have my laptop and desktop inches from each other. So ill run server on linux and then do the rest off windows desktop
Would that work?

**Comment by Pure-L0G1C** [comment]
I already made a video on that. Do everything it Linux except for generating the virus part. Do that part in Windows

**Comment by Rabb2269** [comment]
I did and recieved error above

$python loki.py
Traceback (most recent call last):
  File "loki.py", line 9, in <module>
    from lib.server.server import Server
  File "/home/rabb/Loki/lib/server/server.py", line 8, in <module>
    from lib import const
ImportError: cannot import name const

**Comment by Pure-L0G1C** [comment]
How? What version of Python are you running?

**Comment by Rabb2269** [comment]
Fixed
Feel free to close
